apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hello-world
  name: hello-world
spec:
  serviceAccount: mysvcaccount1
  containers:
  - image: nginx
    name: hello-world
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
